spring:
  profiles:
    default:
      - "consul"
      - "dev"
  application:
    name: bookwarehouse

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
---
# Dev Profile Configuration
server:
  port: 14001
spring:
  config:
    activate:
      on-profile: dev
---
# Prod Profile Configuration
server:
  port: 14001
spring:
  config:
    activate:
      on-profile: prod


